name: Metrics
on:
  schedule:
    - cron: "0 8,20 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: 1Jul1an
          commits_authoring: 1Jul1an

          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Berlin
          config_twemoji: yes

          plugin_introduction: yes
          plugin_introduction_title: About me

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14

          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4

          plugin_calendar: yes
          plugin_habits: yes

          plugin_repositories: yes
          plugin_repositories_featured: |
              1Jul1an/cloud-based-business-intelligence-app,
              1Jul1an/cloud-based-wms-app,
              1Jul1an/storylinewebde,
              1Jul1an/devdrops,
              1Jul1an/linkshelf

          plugin_stargazers: yes
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GEODB_TOKEN }}


      - name: Auto commit
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add github-metrics.svg
            git diff --cached --quiet || git commit -m "Update Metrics"
            git push

